### ISSUE TITLE
Upload file to Releases

### ISSUE THREAD

**Issue by nyanpasu64** [beterhans/x2dcli#2]
You should upload the download to https://github.com/beterhans/x2dcli/releases

**Comment by beterhans** [comment]
Thanks for let me know. I'm not a professional coder Don't know the rule yet.

**Comment by nyanpasu64** [comment]
you technically don't need to put the .7z in Git. Removing it could make managing the source easier (no branch-merge conflicts, for example on pull requests), but may make it harder for people to find the right download (if they don't know how Github works, and don't know how to find the Releases button).

But I think it's more user-friendly to have a binary in Git that you keep up to date, than to keep updating the code without providing a download (which sometimes happens).

AKA this is fine as is.
